# Generated by Django 5.0.1 on 2024-01-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', help_text='Enter a question text', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', help_text='Enter an answer option', verbose_name='Answer option')),
                ('is_right', models.BooleanField(default=False, help_text='Mark the option if it is right answer', verbose_name='Is right')),
                ('test', models.ForeignKey(help_text='Choice question', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
